/* Plugin generated by AMXX-Studio */
#include <amxmodx>
#include <amxmisc>
#include <cstrike>

#define PLUGIN "nobox"
#define VERSION "1.0"
#define AUTHOR "K.."


public plugin_init() {
    register_plugin(PLUGIN, VERSION, AUTHOR)
    
    register_clcmd("say /nobox", "cmd_nobox")
}

public cmd_nobox(id)
{
if (cs_get_user_team(id) == CS_TEAM_CT)
{
server_cmd("mp_friendlyfire 0")
client_print(0, print_chat, "Mano a mano desactivado")
}

return PLUGIN_HANDLED 
} 
