models/summer/001.mdl
models/summer/02.mdl
models/summer/003.mdl
models/summer/3dm_sofa.mdl
models/summer/05.mdl
models/summer/banco.mdl
models/summer/bed.mdl
models/summer/bfcopter.mdl
models/summer/bunkbed.mdl
models/summer/buzzer_pa_tv.mdl
models/summer/cannard.mdl
models/summer/car_sedan.mdl
models/summer/cartons.mdl
models/summer/cashregister.mdl
models/summer/cofee_maker.mdl
models/summer/computer3.mdl
models/summer/copcar2.mdl
models/summer/deadgign.mdl
models/summer/dispensa_1.mdl
models/summer/dispensa_2.mdl
models/summer/filecabinet.mdl
models/summer/filecabinet_4dr-group2.mdl
models/summer/garrafa.mdl
models/summer/garrafas.mdl
models/summer/microwave.mdl
models/summer/phone.mdl
models/summer/sacripan.mdl
models/summer/sink.mdl
models/summer/softdrinks.mdl
models/summer/toilet.mdl
models/summer/vassoura.mdl
models/summer/wdeskchair.mdl
models/summer/women_pfm.mdl
models/summer/xen_trailer.mdl
